name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_blue: ^0.8.0
  intl: any
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  path_provider: '>=0.3.0'
#  flutter_blue:
#    git:
#      url: https://github.com/boskokg/flutter_blue/
#      ref: 0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: any
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: BankGothic
      fonts:
        - asset: fonts/BankGothic Regular.ttf
        - asset: fonts/BankGothic Bold.ttf
          weight: 700
