name: coiote_app
description: Operates Engecomp Coiote board.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_blue: ^0.8.0
  mask_text_input_formatter: ^2.3.0
  inspection: ^0.0.11
  intl: any
  flutter:
    sdk: flutter
  sqflite: any
  http: '>=0.13.4'
  path: any
  path_provider: '>=0.3.0'
#  flutter_blue:
#    git:
#      url: https://github.com/boskokg/flutter_blue/
#      ref: 0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: any
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: BankGothic
      fonts:
        - asset: fonts/BankGothic Regular.ttf
        - asset: fonts/BankGothic Bold.ttf
          weight: 700
